### ISSUE TITLE
considering your nested-unet repository

### ISSUE THREAD

**Issue by IvanVassi** [selmo-lyz/MixtureDensityNetworks#1]
Dear selmo-lyz, I am studying deep learning, in order to understand segmentation and unet I used your nested-unet repository. Unfortunately I can't see it's anymore. Could you please provide access to this code?

**Comment by selmo-lyz** [comment]
I have restored the repository. You can access it now.
But my custom is bad, I cannot confirm the correctness of that implementation nowadays. Sorry.
Therefore, if it's convenient for you, I will recommend you read MrGiovanni (the author) 's code.

**Comment by IvanVassi** [comment]
Great, thank you!
